export const jul17data = {
  breakfast: [
    {
      name: 'Sabji',
      secondaryLanguageName: 'سابجي',
      cost: 0.7,
      price: 0.7,
      categoryId: 2,
      collectionId: 1,
      qwickViewOrder: 1,
      code: 1,
      color: '#eeeeee',
    },
    {
      name: 'Dal ',
      secondaryLanguageName: 'دال',
      cost: 0.7,
      price: 0.7,
      categoryId: 2,
      collectionId: 1,
      qwickViewOrder: 1,
      code: 2,
      color: '#eeeeee',
    },
    {
      name: 'Keema',
      secondaryLanguageName: 'كيما',
      cost: 0.7,
      price: 0.7,
      categoryId: 2,
      collectionId: 1,
      qwickViewOrder: 1,
      code: 3,
      color: '#eeeeee',
    },
    {
      name: 'Egg Tomato ',
      secondaryLanguageName: 'طماطم البيض',
      cost: 0.7,
      price: 0.7,
      categoryId: 2,
      collectionId: 1,
      qwickViewOrder: 1,
      code: 4,
      color: '#eeeeee',
    },
    {
      name: 'Tuna',
      secondaryLanguageName: 'تونة',
      cost: 1,
      price: 1,
      categoryId: 2,
      collectionId: 1,
      qwickViewOrder: 1,
      code: 5,
      color: '#eeeeee',
    },
    {
      name: 'Phoole',
      secondaryLanguageName: 'phoole',
      cost: 0.8,
      price: 0.8,
      categoryId: 2,
      collectionId: 1,
      qwickViewOrder: 1,
      code: 6,
      color: '#eeeeee',
    },
    {
      name: 'Pazoli',
      secondaryLanguageName: 'بازولي',
      cost: 0.8,
      price: 0.8,
      categoryId: 2,
      collectionId: 1,
      qwickViewOrder: 1,
      code: 7,
      color: '#eeeeee',
    },
    {
      name: 'Porotta',
      secondaryLanguageName: 'بوروتا',
      cost: 0.05,
      price: 0.05,
      categoryId: 2,
      collectionId: 1,
      qwickViewOrder: 1,
      code: 8,
      color: '#eeeeee',
    },
    {
      name: 'Chapati',
      secondaryLanguageName: 'تشاباتي',
      cost: 0.05,
      price: 0.05,
      categoryId: 2,
      collectionId: 1,
      qwickViewOrder: 1,
      code: 9,
      color: '#eeeeee',
    },
  ],
  BiriyaniMajboos: [
    {
      name: 'Chicken Biryani ',
      secondaryLanguageName: 'برياني دجاج',
      cost: 1.2,
      price: 1.2,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 7,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: '1/2 Chicken Biriyani',
      secondaryLanguageName: '1/2 دجاج بيرياني',
      cost: 1.7,
      price: 1.7,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 8,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'CB Hyderabadi',
      secondaryLanguageName: 'CB Hyderabadi',
      cost: 1.2,
      price: 1.2,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 9,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: '1/2 CB Hyderabadi',
      secondaryLanguageName: '1/2 CB Hyderabadi',
      cost: 1.7,
      price: 1.7,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 10,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mutton Biriyani',
      secondaryLanguageName: 'لحم الضأن بيرياني',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 11,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'K Biriyani',
      secondaryLanguageName: 'ك برياني',
      cost: 2,
      price: 2,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 12,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Shey Biriyani',
      secondaryLanguageName: 'شيري بيرياني',
      cost: 2,
      price: 2,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 13,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Rubiyan Biriyani',
      secondaryLanguageName: 'روبيان بيرياني',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 14,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Neher Biriyani',
      secondaryLanguageName: 'نهر بيرياني',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 15,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N Biriyani',
      secondaryLanguageName: 'r/n biriyani',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 16,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Fish Biriyani',
      secondaryLanguageName: 'السمك بيرياني',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 17,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Majboos',
      secondaryLanguageName: 'ج ماجبو',
      cost: 1.2,
      price: 1.2,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 18,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: '1/2 C Majboos',
      secondaryLanguageName: '1/2 ج ماجبو',
      cost: 1.7,
      price: 1.7,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 19,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mutton Majboos',
      secondaryLanguageName: 'لحم الضأن ماجبو',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 20,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Kenal Majboos',
      secondaryLanguageName: 'كينال ماجبو',
      cost: 2,
      price: 2,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 21,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Shery Majboos',
      secondaryLanguageName: 'شيري ماجبو',
      cost: 2,
      price: 2,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 22,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Fish Majboos',
      secondaryLanguageName: 'ماجبو السمك',
      cost: 2,
      price: 2,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 23,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Rubian Majboos',
      secondaryLanguageName: 'روبيان ماجبو',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 24,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Neher Majboos',
      secondaryLanguageName: 'Neher Majboos',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 25,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N Majboos',
      secondaryLanguageName: 'R/N Majboos',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 26,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Prans Majboos',
      secondaryLanguageName: 'و prans majboos',
      cost: 2.5,
      price: 2.5,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 27,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Prans Biriyani',
      secondaryLanguageName: 'و prans biriyani',
      cost: 2.5,
      price: 2.5,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 28,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'B Rice',
      secondaryLanguageName: 'الأرز ب',
      cost: 0.7,
      price: 0.7,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 29,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'M Rice',
      secondaryLanguageName: 'م الأرز',
      cost: 0.7,
      price: 0.7,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 30,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'W Rice',
      secondaryLanguageName: 'أرز',
      cost: 0.6,
      price: 0.6,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 31,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'B Rice Small',
      secondaryLanguageName: 'B الأرز صغير',
      cost: 0.3,
      price: 0.3,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 32,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'CF Rice',
      secondaryLanguageName: 'رايس رايس',
      cost: 1.5,
      price: 1.5,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 33,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mix F Rice',
      secondaryLanguageName: 'خلط F الأرز',
      cost: 1.8,
      price: 1.8,
      categoryId: 3,
      qwickViewOrder: 2,
      code: 34,
      color: '#eeeeee',
      collectionId: 1,
    },
  ],
  DuBiriyani: [
    {
      name: 'C Dum',
      secondaryLanguageName: 'ج دوم',
      cost: 1.2,
      price: 1.2,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 35,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'B Dum',
      secondaryLanguageName: 'ب دوم',
      cost: 1.7,
      price: 1.7,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 36,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mutton Dum',
      secondaryLanguageName: 'لحم الضأن دوم',
      cost: 1.8,
      price: 1.8,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 37,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Kenal Dum',
      secondaryLanguageName: 'كينال دوم',
      cost: 2,
      price: 2,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 38,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Prans Dum',
      secondaryLanguageName: 'برانس دوم',
      cost: 1.8,
      price: 1.8,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 39,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Prans Dum',
      secondaryLanguageName: 'و prans dum',
      cost: 2.5,
      price: 2.5,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 40,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Shery Dum',
      secondaryLanguageName: 'شيري دوم',
      cost: 2.5,
      price: 2.5,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 41,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Fish Dum',
      secondaryLanguageName: 'السمك',
      cost: 2.5,
      price: 2.5,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 42,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Biriyani Masala',
      secondaryLanguageName: 'C Biriyani Masala',
      cost: 1.2,
      price: 1.2,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 43,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Beef Biriyani Masala',
      secondaryLanguageName: 'لحوم البقر بيرياني ماسالا',
      cost: 1.7,
      price: 1.7,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 44,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mutton Biriyani Masala',
      secondaryLanguageName: 'لحم الضأن برياني ماسالا',
      cost: 1.8,
      price: 1.8,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 45,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'K Biriyani Masala',
      secondaryLanguageName: 'ك برياني ماسالا',
      cost: 2,
      price: 2,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 46,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Veg Biriyani',
      secondaryLanguageName: 'الخضار بيرياني',
      cost: 1.1,
      price: 1.1,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 47,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Dum B Rice',
      secondaryLanguageName: 'أرز دوم ب',
      cost: 0.7,
      price: 0.7,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 48,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Gee Rice',
      secondaryLanguageName: 'أرز جي',
      cost: 0.7,
      price: 0.7,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 49,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Dum B rice small',
      secondaryLanguageName: 'أرز دوم ب صغير',
      cost: 0.3,
      price: 0.3,
      categoryId: 4,
      qwickViewOrder: 3,
      code: 50,
      color: '#eeeeee',
      collectionId: 1,
    },
  ],
  Arabic: [
    {
      name: 'C Nashif',
      secondaryLanguageName: 'ج ناشيف',
      cost: 1.4,
      price: 1.4,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 42,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Butter Chicken',
      secondaryLanguageName: 'الدجاج الزبدة',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 43,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Kusasi',
      secondaryLanguageName: 'C Kusasi',
      cost: 1.3,
      price: 1.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 44,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C chilly',
      secondaryLanguageName: 'ج باردة',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 45,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C 65',
      secondaryLanguageName: 'ج 65',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 46,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C smoked',
      secondaryLanguageName: 'ج مدخن',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 47,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C ginger gardlic',
      secondaryLanguageName: 'ج جاردينك جاركلك',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 48,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Manchoorian',
      secondaryLanguageName: 'C Manchoorian',
      cost: 1.6,
      price: 1.6,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 49,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Masala',
      secondaryLanguageName: 'ج ماسالا',
      cost: 1.3,
      price: 1.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 50,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Tava',
      secondaryLanguageName: 'ج تافا',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 51,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'D Sepili Chicken',
      secondaryLanguageName: 'د الدجاج سيبيلي',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 52,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Amoose Shawarma',
      secondaryLanguageName: 'Amoose Shawarma',
      cost: 1,
      price: 1,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 53,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R Nashif',
      secondaryLanguageName: 'ص ناشيف',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 54,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Rubiyan Butter',
      secondaryLanguageName: 'زبدة روبيان',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 55,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Rubian Chilly',
      secondaryLanguageName: 'روبيان بارد',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 56,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Rubiyan 65',
      secondaryLanguageName: 'روبيان 65',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 57,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Rubian Masala',
      secondaryLanguageName: 'روبيان ماسالا',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 58,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Rubian Machooriyan',
      secondaryLanguageName: 'روبيان ماتشوريان',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 59,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R Smocked',
      secondaryLanguageName: 'ص مدخن',
      cost: 1.8,
      price: 1.8,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 60,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R Magil amoose',
      secondaryLanguageName: 'ص ماجيل أموز',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 61,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar Nashif',
      secondaryLanguageName: 'نهر ناشيف',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 62,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar Butter',
      secondaryLanguageName: 'زبدة نهر',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 63,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar Chilly',
      secondaryLanguageName: 'نهر بارد',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 64,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar 65',
      secondaryLanguageName: 'نهر 65',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 65,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar Smoked',
      secondaryLanguageName: 'نهر يدخن',
      cost: 1.8,
      price: 1.8,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 66,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar Manjoorian',
      secondaryLanguageName: 'نهر مانجوريان',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 67,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar Masala',
      secondaryLanguageName: 'نهر ماسالا',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 68,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar Ginger Garlic',
      secondaryLanguageName: 'ثوم جينجر نهر',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 69,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar Magli Amoose',
      secondaryLanguageName: 'نهر ماجلي أموز',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 70,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/Nehar Nashif',
      secondaryLanguageName: 'ص/نهر ناشيف',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 71,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N Butter',
      secondaryLanguageName: 'ص/زبدة',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 72,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N chilly',
      secondaryLanguageName: 'ص/ن بارد',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 73,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N Smoked',
      secondaryLanguageName: 'R/N مدخن',
      cost: 1.8,
      price: 1.8,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 74,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N Masala',
      secondaryLanguageName: 'R/N Masala',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 75,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N Magli Hammose',
      secondaryLanguageName: 'R/N Magli Hammose',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 76,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N Manjoorian',
      secondaryLanguageName: 'ص/ن مانجوريان',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 77,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N 65',
      secondaryLanguageName: 'ص/ن 65',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 78,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R/N Ginger Garlic',
      secondaryLanguageName: 'ص/نجر الثوم',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 79,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Rubiyan Nashif',
      secondaryLanguageName: 'و روبيان ناشيف',
      cost: 2.3,
      price: 2.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 80,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Rubian Butter',
      secondaryLanguageName: 'زبدة روبيان',
      cost: 2.3,
      price: 2.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 81,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Rubian Masala',
      secondaryLanguageName: 'و روبيان ماسالا',
      cost: 2.3,
      price: 2.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 82,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Rubian Chilly',
      secondaryLanguageName: 'و روبيان بارد',
      cost: 2.3,
      price: 2.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 83,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Rubina 65',
      secondaryLanguageName: 'F Rubina 65',
      cost: 2.3,
      price: 2.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 84,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Rubian Smoked',
      secondaryLanguageName: 'و روبيان يدخن',
      cost: 2.3,
      price: 2.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 85,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Rubian Manjoorian',
      secondaryLanguageName: 'و روبيان مانجوريان',
      cost: 2.3,
      price: 2.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 86,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Rubian Magli Ammose',
      secondaryLanguageName: 'و روبيان ماجلي',
      cost: 2.3,
      price: 2.3,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 87,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nakenak Nashif',
      secondaryLanguageName: 'ناكيناك ناشيف',
      cost: 1,
      price: 1,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 88,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nakenak Masala',
      secondaryLanguageName: 'ناكيناك ماسالا',
      cost: 1.2,
      price: 1.2,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 89,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nakenak Butter',
      secondaryLanguageName: 'زبدة ناكيناك',
      cost: 1.2,
      price: 1.2,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 90,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nakenak Magli Ammose',
      secondaryLanguageName: 'Nakenak Magli Ammose',
      cost: 1.2,
      price: 1.2,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 91,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nakenak Chilly',
      secondaryLanguageName: 'نياك بارد',
      cost: 1.2,
      price: 1.2,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 92,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Lahem Nashif',
      secondaryLanguageName: 'لاهيم ناشيف',
      cost: 1.4,
      price: 1.4,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 93,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Hammose Leham',
      secondaryLanguageName: 'هامس ليهام',
      cost: 1.4,
      price: 1.4,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 94,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Beef Butter',
      secondaryLanguageName: 'زبدة لحوم البقر',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 95,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Egg Tomato',
      secondaryLanguageName: 'طماطم البيض',
      cost: 0.7,
      price: 0.7,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 96,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mutton Masala',
      secondaryLanguageName: 'لحم الضأن ماسالا',
      cost: 1.5,
      price: 1.5,
      categoryId: 5,
      qwickViewOrder: 2,
      code: 97,
      color: '#eeeeee',
      collectionId: 1,
    },
  ],
  Indian: [
    {
      name: 'Beef Rost',
      secondaryLanguageName: 'لحم البقر',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 98,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Beef Fry',
      secondaryLanguageName: 'بقرية لحوم البقر',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 99,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Beef Curry',
      secondaryLanguageName: 'لحم البقر بالكاري',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 100,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Liver',
      secondaryLanguageName: 'الكبد',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 101,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Botti',
      secondaryLanguageName: 'بوتي',
      cost: 1.3,
      price: 1.3,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 102,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Duck',
      secondaryLanguageName: 'بطة',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 103,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Ayla Curry',
      secondaryLanguageName: 'Ayla كاري',
      cost: 1.2,
      price: 1.2,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 104,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Avoli Curry',
      secondaryLanguageName: 'أفولي كاري',
      cost: 1.4,
      price: 1.4,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 105,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mutton Pepper',
      secondaryLanguageName: 'فلفل لحم الضأن',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 106,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Crab',
      secondaryLanguageName: 'سلطعون',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 107,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Koonthel Rost',
      secondaryLanguageName: 'Koonthel Rost',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 108,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Pepper Masala',
      secondaryLanguageName: 'ج الفلفل ماسالا',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 109,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Kadai',
      secondaryLanguageName: 'ج كاداي',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 110,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Chilly',
      secondaryLanguageName: 'ج باردة',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 111,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C 65',
      secondaryLanguageName: 'ج 65',
      cost: 1.4,
      price: 1.4,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 112,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Kerala',
      secondaryLanguageName: 'ج كيرالا',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 113,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Asiyana',
      secondaryLanguageName: 'C Asiyana',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 114,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Kuruma',
      secondaryLanguageName: 'ج كوروما',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 115,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Chettinadu',
      secondaryLanguageName: 'C Chettinadu',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 116,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Chicken Stew',
      secondaryLanguageName: 'حساء الدجاج',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 117,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Chicken Rost',
      secondaryLanguageName: 'دجاج روست',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 118,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Pepper Chilly',
      secondaryLanguageName: 'الفلفل بارد',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 119,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Smoked',
      secondaryLanguageName: 'ج مدخن',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 120,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Fish Rost',
      secondaryLanguageName: 'صخور الأسماك',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 121,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Prans Rost',
      secondaryLanguageName: 'برانس روست',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 122,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'F Prans Rost',
      secondaryLanguageName: 'و prans rost',
      cost: 2.3,
      price: 2.3,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 123,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Chicken Sachwan',
      secondaryLanguageName: 'دجاج ساشوان',
      cost: 1.5,
      price: 1.5,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 124,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Chicken Masala',
      secondaryLanguageName: 'دجاج ماسالا',
      cost: 1.3,
      price: 1.3,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 125,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Vej Kuruma',
      secondaryLanguageName: 'فيج كوروما',
      cost: 0.8,
      price: 0.8,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 126,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Paneer Masala',
      secondaryLanguageName: 'بانير ماسالا',
      cost: 1.2,
      price: 1.2,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 127,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Paneel Butter',
      secondaryLanguageName: 'زبدة paneel',
      cost: 1.2,
      price: 1.2,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 128,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Paneer Kadai',
      secondaryLanguageName: 'بانير كاداي',
      cost: 1.2,
      price: 1.2,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 129,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Paneer Buruji',
      secondaryLanguageName: 'بانير بوروجي',
      cost: 1.2,
      price: 1.2,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 130,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mashroom Masala',
      secondaryLanguageName: 'مهجور ماسالا',
      cost: 1.2,
      price: 1.2,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 131,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mashroom Kadai',
      secondaryLanguageName: 'المهجور كاداي',
      cost: 1.2,
      price: 1.2,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 132,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Gobi Manjoorian',
      secondaryLanguageName: 'جوبي مانجوريان',
      cost: 1.2,
      price: 1.2,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 133,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Chilly Gobi',
      secondaryLanguageName: 'جوبي البارد',
      cost: 1.2,
      price: 1.2,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 134,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Egg Burji',
      secondaryLanguageName: 'بيضة بورجي',
      cost: 0.8,
      price: 0.8,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 135,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Porotta',
      secondaryLanguageName: 'بوروتا',
      cost: 0.05,
      price: 0.05,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 136,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Atta Porotta',
      secondaryLanguageName: 'عطا بوروتا',
      cost: 0.05,
      price: 0.05,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 137,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Chapati',
      secondaryLanguageName: 'تشاباتي',
      cost: 0.05,
      price: 0.05,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 138,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Idiyappam',
      secondaryLanguageName: 'Idiyappam',
      cost: 0.1,
      price: 0.1,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 139,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Kappa',
      secondaryLanguageName: 'كابا',
      cost: 0.4,
      price: 0.4,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 140,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Gee Rice',
      secondaryLanguageName: 'أرز جي',
      cost: 0.7,
      price: 0.7,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 141,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'W Rice',
      secondaryLanguageName: 'أرز',
      cost: 0.7,
      price: 0.7,
      categoryId: 6,
      qwickViewOrder: 4,
      code: 142,
      color: '#eeeeee',
      collectionId: 1,
    },
  ],
  RiceGravy: [
    {
      name: 'Butter C Rice',
      secondaryLanguageName: 'زبدة الأرز',
      cost: 1.8,
      price: 1.8,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 143,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mutton Masala Rice',
      secondaryLanguageName: 'لحم الضأن ماسالا الأرز',
      cost: 1.8,
      price: 1.8,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 144,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Rubian Masala Rice',
      secondaryLanguageName: 'أرز روبيان ماسالا',
      cost: 1.8,
      price: 1.8,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 145,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Fish Masala Rice',
      secondaryLanguageName: 'الأرز ماسالا السمك',
      cost: 1.8,
      price: 1.8,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 146,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'R Butter Rice',
      secondaryLanguageName: 'ردة الأرز',
      cost: 1.8,
      price: 1.8,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 147,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Masala Rice',
      secondaryLanguageName: 'ج ماسالا الأرز',
      cost: 1.5,
      price: 1.5,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 148,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Nehar Masala Rice',
      secondaryLanguageName: 'رايس نهر ماسالا',
      cost: 1.8,
      price: 1.8,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 149,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Ghee Rice Beef rost',
      secondaryLanguageName: 'السمن رايس لحم البقر rost',
      cost: 1.8,
      price: 1.8,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 150,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'G Rice C Curry',
      secondaryLanguageName: 'G الأرز C Curry',
      cost: 1.8,
      price: 1.8,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 151,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'B Rice',
      secondaryLanguageName: 'الأرز ب',
      cost: 0.7,
      price: 0.7,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 152,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'W Rice',
      secondaryLanguageName: 'أرز',
      cost: 0.7,
      price: 0.7,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 153,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'G Rice',
      secondaryLanguageName: 'رايس',
      cost: 0.7,
      price: 0.7,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 154,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Rice Small',
      secondaryLanguageName: 'الأرز صغير',
      cost: 0.3,
      price: 0.3,
      categoryId: 7,
      qwickViewOrder: 4,
      code: 155,
      color: '#eeeeee',
      collectionId: 1,
    },
  ],
  Chinese: [
    {
      name: 'C Fried Rice',
      secondaryLanguageName: 'ج الأرز المقلي',
      cost: 1.5,
      price: 1.5,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 156,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Veg Fried Rice',
      secondaryLanguageName: 'الأرز الخضار المقلي',
      cost: 1.2,
      price: 1.2,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 157,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Egg Fried Rice',
      secondaryLanguageName: 'الأرز المقلي البيض',
      cost: 1.3,
      price: 1.3,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 158,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Mix Fried Rice',
      secondaryLanguageName: 'خلط الأرز المقلي',
      cost: 1.8,
      price: 1.8,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 159,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'Seshwan Fried Rice',
      secondaryLanguageName: 'سيشوان الأرز المقلي',
      cost: 1.8,
      price: 1.8,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 160,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Chilly',
      secondaryLanguageName: 'ج باردة',
      cost: 1.5,
      price: 1.5,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 161,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Manjoorian',
      secondaryLanguageName: 'ج مانجوريان',
      cost: 1.5,
      price: 1.5,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 162,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C Smoked',
      secondaryLanguageName: 'ج مدخن',
      cost: 1.5,
      price: 1.5,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 163,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'C 65',
      secondaryLanguageName: 'ج 65',
      cost: 1.4,
      price: 1.4,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 164,
      color: '#eeeeee',
      collectionId: 1,
    },
    {
      name: 'W Rice',
      secondaryLanguageName: 'أرز',
      cost: 0.7,
      price: 0.7,
      categoryId: 8,
      qwickViewOrder: 33,
      code: 165,
      color: '#eeeeee',
      collectionId: 1,
    },
  ],
};
