import { Prisma } from '@prisma/client';

export const companyData = {
  name: 'Dawar Zadna Restaurant',
  arabic: 'ARabic dawar Zadna',
  logoUrl: 'logo url',
  lastOrderNumber: 10,
  caption: 'Taske dies right here',
  footer: 'Tasty footer',
  currencyCode: 'OMR',
  address: 'Falaj al Quabail',
  taxes: {
    create: [{ name: 'VAT', printName: 'VAT', isPercentage: true, value: 5.0 }],
  },
};

export const collectionData: Prisma.collectionCreateInput = {
  name: 'Arabian',
};
// export const kitchenData = {
//   name: 'Juice Counter',
//   printer: 'QAS',
// };
export const categoryData: Prisma.categoryCreateInput[] = [
  {
    name: 'Mutton',
    color: '#dedede',
    kitchen: {
      create: {
        name: 'Main',
        printer: 'main',
      },
    },
    isAvailableAllDay: true,
    startTime: '10 pm',
    endTime: '11am',
    products: {
      create: [
        {
          name: 'Mutton Chaps',
          secondaryLanguageName: 'لحم الضأن',
          collectionId: 1,
          cost: 1.7,
          price: 1.7,
        },
        {
          name: 'Mutton Masala',
          secondaryLanguageName: 'لحم الضأن ماسالا',
          collectionId: 1,
          cost: 1.7,
          price: 1.7,
        },
        {
          name: 'Mutton Pepper Masala',
          secondaryLanguageName: 'لحم الضأن الفلفل ماسالا',
          collectionId: 1,
          cost: 1.8,
          price: 1.8,
        },
        {
          name: 'Mutton Pepper Chilly',
          secondaryLanguageName: 'لحم الضأن الفلفل البارد',
          collectionId: 1,
          cost: 1.8,
          price: 1.8,
        },
        {
          name: 'Botti',
          secondaryLanguageName: 'بوتي',
          collectionId: 1,
          cost: 1.4,
          price: 1.4,
        },
        {
          name: 'Mutton Kuruma',
          secondaryLanguageName: 'لحم الضأن كوروما',
          collectionId: 1,
          cost: 1.7,
          price: 1.7,
        },
        {
          name: 'Mutton Stew',
          secondaryLanguageName: 'حساء لحم الضأن',
          collectionId: 1,
          cost: 1.7,
          price: 1.7,
        },
      ],
    },
  },
  {
    name: 'Fish',
    color: '#fefeef',
    kitchen: {
      create: {
        name: 'SecondK',
        printer: 'Main',
      },
    },
    isAvailableAllDay: true,
    startTime: '10 pm',
    endTime: '11am',
    products: {
      create: [
        {
          name: 'Fish Chilli',
          secondaryLanguageName: 'الفلفل الحار السمك',
          collectionId: 1,
          cost: 1.6,
          price: 1.6,
        },
        {
          name: 'Fish Masala',
          secondaryLanguageName: 'سمك ماسالا',
          collectionId: 1,
          cost: 1.6,
          price: 1.6,
        },
        {
          name: 'Fish Manchurian',
          secondaryLanguageName: 'الأسماك manchurian',
          collectionId: 1,
          cost: 1.6,
          price: 1.6,
        },
        {
          name: 'Fish Fry',
          secondaryLanguageName: 'سمك مقلي',
          collectionId: 1,
          cost: 1.8,
          price: 1.8,
        },
        {
          name: 'Squid',
          secondaryLanguageName: 'حبار',
          collectionId: 1,
          cost: 1.5,
          price: 1.5,
        },
        {
          name: 'Crab',
          secondaryLanguageName: 'سلطعون',
          collectionId: 1,
          cost: 1.6,
          price: 1.6,
        },
      ],
    },
  },
];

export const data = {
  Mutton: [
    {
      _id: '101',
      name: 'Mutton Chaps',
      arabicName: 'كيف حالك',
      description: 'Test Description',
      category: 'MUTTON',
      onSale: false,
      price: 1.7,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
      modifiers: [{ name: 'hello modifier', price: 11.1 }],
      quickDisplayOrder: 2,
    },
    {
      _id: '102',
      name: 'Mutton Masala',
      arabicName: 'كيف حالك',
      description: 'Test Description',
      category: 'MUTTON',
      onSale: false,
      price: 1.7,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '103',
      name: 'Mutton Pepper Masala',
      description: 'Test Description',
      category: 'MUTTON',
      onSale: false,
      price: 1.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '104',
      name: 'Mutton Pepper Chilly',
      description: 'Test Description',
      category: 'MUTTON',
      onSale: false,
      price: 1.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '105',
      name: 'Botti',
      description: 'Test Description',
      category: 'MUTTON',
      onSale: false,
      price: 1.4,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '106',
      name: 'Mutton Kuruma',
      description: 'Test Description',
      category: 'MUTTON',
      onSale: false,
      price: 1.7,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '107',
      name: 'Mutton Stew',
      description: 'Test Description',
      category: 'MUTTON',
      onSale: false,
      price: 1.7,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
      quickDisplayOrder: 11,
    },
  ],
  Fish: [
    {
      _id: '164',
      name: 'Fish Chilli',
      description: 'Test Description',
      category: 'FISH',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '165',
      name: 'Fish Masala',
      description: 'Test Description',
      category: 'FISH',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
      quickDisplayOrder: 1,
    },
    {
      _id: '166',
      name: 'Fish Manchurian',
      description: 'Test Description',
      category: 'FISH',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '167',
      name: 'Fish Fry',
      description: 'Test Description',
      category: 'FISH',
      onSale: false,
      price: 1.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '168',
      name: 'Squid',
      description: 'Test Description',
      category: 'FISH',
      onSale: false,
      price: 1.5,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '169',
      name: 'Crab',
      description: 'Test Description',
      category: 'FISH',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
  ],
  Juice: [
    {
      _id: '176',
      name: 'Watermelon M',
      description: 'Test Description',
      category: 'JUICE',
      onSale: false,
      price: 0.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '177',
      name: 'Watermelon L',
      description: 'Test Description',
      category: 'JUICE',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
      quickDisplayOrder: 15,
    },
    {
      _id: '178',
      name: 'Orange M',
      description: 'Test Description',
      category: 'JUICE',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '179',
      name: 'Orange L',
      description: 'Test Description',
      category: 'JUICE',
      onSale: false,
      price: 1,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '180',
      name: 'Avocado M',
      description: 'Test Description',
      category: 'JUICE',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '181',
      name: 'Avocado L',
      description: 'Test Description',
      category: 'JUICE',
      onSale: false,
      price: 1,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
      quickDisplayOrder: 4,
    },
    {
      _id: '182',
      name: 'Mango Pomogranate M',
      description: 'Test Description',
      category: 'JUICE',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '183',
      name: 'Mango Pomogranate L',
      description: 'Test Description',
      category: 'JUICE',
      onSale: false,
      price: 1,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '222',
      name: 'Lichi',
      description: 'Test Description',
      category: 'JUICE',
      onSale: false,
      price: 1,
      isAvailable: true,
      archived: false,
      popular: true,
      modifiers: [{ name: 'sprinkled chees', price: 0.2 }],
      variants: [
        {
          name: 'Small',
          price: 2.0,
        },
        {
          name: 'Medium',
          price: 2.2,
        },
        {
          name: 'Large',
          price: 2.9,
        },
      ],
      image: '["test","fast"]',
    },
  ],
  Breakfast: [
    {
      _id: '132',
      name: 'Egg and Tomato',
      description: 'Test Description',
      category: 'BREAKFAST',
      onSale: false,
      price: 0.7,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
      quickDisplayOrder: 5,
    },
    {
      _id: '133',
      name: 'Keema',
      description: 'Test Description',
      category: 'BREAKFAST',
      onSale: false,
      price: 0.7,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '134',
      name: 'Dal',
      description: 'Test Description',
      category: 'BREAKFAST',
      onSale: false,
      price: 0.7,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '135',
      name: 'Sabji',
      description: 'Test Description',
      category: 'BREAKFAST',
      onSale: false,
      price: 0.7,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '136',
      name: 'Tuna',
      description: 'Test Description',
      category: 'BREAKFAST',
      onSale: false,
      price: 1.2,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '137',
      name: 'Phool',
      description: 'Test Description',
      category: 'BREAKFAST',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '138',
      name: 'Pazoli',
      description: 'Test Description',
      category: 'BREAKFAST',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '139',
      name: 'Egg Masala',
      description: 'Test Description',
      category: 'BREAKFAST',
      onSale: false,
      price: 0.7,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
  ],
  Roti: [
    {
      _id: '140',
      name: 'Porotta',
      description: 'Test Description',
      category: 'ROTI',
      onSale: false,
      price: 0.075,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '141',
      name: 'Atta Porotta',
      description: 'Test Description',
      category: 'ROTI',
      onSale: false,
      price: 0.075,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '142',
      name: 'Chapathy',
      description: 'Test Description',
      category: 'ROTI',
      onSale: false,
      price: 0.075,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '143',
      name: 'Idiyappam',
      description: 'Test Description',
      category: 'ROTI',
      onSale: false,
      price: 0.1,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '144',
      name: 'Puttu',
      description: 'Test Description',
      category: 'ROTI',
      onSale: false,
      price: 0.3,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '145',
      name: 'Kappa',
      description: 'Test Description',
      category: 'ROTI',
      onSale: false,
      price: 0.4,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
  ],
  Soup: [
    {
      _id: '146',
      name: 'Seafood Soup',
      description: 'Test Description',
      category: 'SOUP',
      onSale: false,
      price: 1.3,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '147',
      name: 'Sweet Corn Chicken Soup',
      description: 'Test Description',
      category: 'SOUP',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '148',
      name: 'Sweet Corn Veg Soup',
      description: 'Test Description',
      category: 'SOUP',
      onSale: false,
      price: 0.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '149',
      name: 'Manchow Soup',
      description: 'Test Description',
      category: 'SOUP',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '150',
      name: 'Hto and Sour Soup',
      description: 'Test Description',
      category: 'SOUP',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
  ],
  Salad: [
    {
      _id: '151',
      name: 'Fathoush',
      description: 'Test Description',
      category: 'SALAD',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '152',
      name: 'Arabic Salad',
      description: 'Test Description',
      category: 'SALAD',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '153',
      name: 'Fresh Green Salad',
      description: 'Test Description',
      category: 'SALAD',
      onSale: false,
      price: 0.8,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '154',
      name: 'Dawar Special Salad',
      description: 'Test Description',
      category: 'SALAD',
      onSale: false,
      price: 1,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '155',
      name: 'Hammous - S',
      description: 'Test Description',
      category: 'SALAD',
      onSale: false,
      price: 0.3,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '156',
      name: 'Hammous',
      description: 'Test Description',
      category: 'SALAD',
      onSale: false,
      price: 0.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
  ],
  Squid: [
    {
      _id: '119',
      name: 'Squid Nashif',
      description: 'Test Description',
      category: 'SQUID',
      onSale: false,
      price: 1.5,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '120',
      name: 'Buttor Squid',
      description: 'Test Description',
      category: 'SQUID',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '121',
      name: 'Squid Chilly',
      description: 'Test Description',
      category: 'SQUID',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '122',
      name: 'Squid Masala',
      description: 'Test Description',
      category: 'SQUID',
      onSale: false,
      price: 1.5,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '123',
      name: 'Squid Fry',
      description: 'Test Description',
      category: 'SQUID',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '124',
      name: 'Squid Roast',
      description: 'Test Description',
      category: 'SQUID',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '125',
      name: 'Squid Manchurian',
      description: 'Test Description',
      category: 'SQUID',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '126',
      name: 'Squid Ginger/Garlic',
      description: 'Test Description',
      category: 'SQUID',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '127',
      name: 'Squid Pepper',
      description: 'Test Description',
      category: 'SQUID',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
  ],
  Sousage: [
    {
      _id: '128',
      name: 'Sausage Nashif',
      description: 'Test Description',
      category: 'SAUSAGE',
      onSale: false,
      price: 1.2,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '129',
      name: 'Sausage Chilly',
      description: 'Test Description',
      category: 'SAUSAGE',
      onSale: false,
      price: 1.3,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '130',
      name: 'Sausage Butter',
      description: 'Test Description',
      category: 'SAUSAGE',
      onSale: false,
      price: 1.4,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '131',
      name: 'Sausage Masala',
      description: 'Test Description',
      category: 'SAUSAGE',
      onSale: false,
      price: 1.3,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
  ],
  Beef: [
    {
      _id: '108',
      name: 'Beef Chilly',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.5,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '109',
      name: 'Beef Butter',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '110',
      name: 'Beef Nashif',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.3,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '111',
      name: 'Beef Masala',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.5,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '112',
      name: 'Beef Fry',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.5,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '113',
      name: 'Beef Dry Fry',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.5,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '114',
      name: 'Beef Manchurian',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '115',
      name: 'Fresh Beef Roast',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.5,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '116',
      name: 'Beef Peer',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '117',
      name: 'Ginger Garlic Beef',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '118',
      name: 'Liver',
      description: 'Test Description',
      category: 'BEEF',
      onSale: false,
      price: 1.5,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
  ],
  Hammous: [
    {
      _id: '170',
      name: 'Hammous Shawarma',
      description: 'Test Description',
      category: 'HAMMOUS',
      onSale: false,
      price: 1.2,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '171',
      name: 'Hammous Chicken',
      description: 'Test Description',
      category: 'HAMMOUS',
      onSale: false,
      price: 1.4,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '172',
      name: 'Hammous Squid',
      description: 'Test Description',
      category: 'HAMMOUS',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '173',
      name: 'Hammous Sausage',
      description: 'Test Description',
      category: 'HAMMOUS',
      onSale: false,
      price: 1.4,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '174',
      name: 'Hammous Prawns',
      description: 'Test Description',
      category: 'HAMMOUS',
      onSale: false,
      price: 1.6,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
    {
      _id: '175',
      name: 'Hammous Beef',
      description: 'Test Description',
      category: 'HAMMOUS',
      onSale: false,
      price: 1.4,
      isAvailable: true,
      archived: false,
      popular: true,
      image: '["test","fast"]',
    },
  ],
};
