import { Prisma } from '@prisma/client';

export const testSample: Prisma.productCreateManyArgs = {
  data: [
    {
      name: 'Mutton Chaps',
      secondaryLanguageName: 'لحم الضأن',
      collectionId: 1,
      categoryId: 1,
      cost: 1.7,
      price: 1.7,
    },
    {
      name: 'Mutton Masala',
      secondaryLanguageName: 'لحم الضأن ماسالا',
      collectionId: 1,
      categoryId: 1,
      cost: 1.7,
      price: 1.7,
    },
  ],
};

export const productData = {
  data: [
    {
      name: 'Mutton Chaps',
      secondaryLanguageName: 'لحم الضأن',
      collectionId: 1,
      categoryId: 1,
      cost: 1.7,
      price: 1.7,
    },
    {
      name: 'Mutton Masala',
      secondaryLanguageName: 'لحم الضأن ماسالا',
      collectionId: 1,
      categoryId: 1,
      cost: 1.7,
      price: 1.7,
    },
    {
      name: 'Mutton Pepper Masala',
      secondaryLanguageName: 'لحم الضأن الفلفل ماسالا',
      collectionId: 1,
      categoryId: 1,
      cost: 1.8,
      price: 1.8,
    },
    {
      name: 'Mutton Pepper Chilly',
      secondaryLanguageName: 'لحم الضأن الفلفل البارد',
      collectionId: 1,
      categoryId: 1,
      cost: 1.8,
      price: 1.8,
    },
    {
      name: 'Botti',
      secondaryLanguageName: 'بوتي',
      collectionId: 1,
      categoryId: 1,
      cost: 1.4,
      price: 1.4,
    },
    {
      name: 'Mutton Kuruma',
      secondaryLanguageName: 'لحم الضأن كوروما',
      collectionId: 1,
      categoryId: 1,
      cost: 1.7,
      price: 1.7,
    },
    {
      name: 'Mutton Stew',
      secondaryLanguageName: 'حساء لحم الضأن',
      collectionId: 1,
      categoryId: 1,
      cost: 1.7,
      price: 1.7,
    },
    {
      name: 'Fish Chilli',
      secondaryLanguageName: 'الفلفل الحار السمك',
      collectionId: 1,
      categoryId: 2,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Fish Masala',
      secondaryLanguageName: 'سمك الماسالا',
      collectionId: 1,
      categoryId: 2,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Fish Manchurian',
      secondaryLanguageName: 'السمك manchurian',
      collectionId: 1,
      categoryId: 2,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Fish Fry',
      secondaryLanguageName: 'سمك مقلي',
      collectionId: 1,
      categoryId: 2,
      cost: 1.8,
      price: 1.8,
    },
    {
      name: 'Squid',
      secondaryLanguageName: 'حبار',
      collectionId: 1,
      categoryId: 2,
      cost: 1.5,
      price: 1.5,
    },
    {
      name: 'Crab',
      secondaryLanguageName: 'سلطعون',
      collectionId: 1,
      categoryId: 2,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Watermelon',
      secondaryLanguageName: 'بطيخ',
      collectionId: 1,
      categoryId: 3,
      cost: 0.6,
      price: 0.6,
    },
    {
      name: 'Orange',
      secondaryLanguageName: 'البرتقالي',
      collectionId: 1,
      categoryId: 3,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Avocado',
      secondaryLanguageName: 'أفوكادو',
      collectionId: 1,
      categoryId: 3,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Avocado',
      secondaryLanguageName: 'أفوكادو',
      collectionId: 1,
      categoryId: 3,
      cost: 1,
      price: 1,
    },
    {
      name: 'Mango Pomogranate',
      secondaryLanguageName: 'المانجو بوموجرانت',
      collectionId: 1,
      categoryId: 3,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Egg and Tomato',
      secondaryLanguageName: 'البيض والطماطم',
      collectionId: 1,
      categoryId: 4,
      cost: 0.7,
      price: 0.7,
    },
    {
      name: 'Keema',
      secondaryLanguageName: 'كيما',
      collectionId: 1,
      categoryId: 4,
      cost: 0.7,
      price: 0.7,
    },
    {
      name: 'Dal',
      secondaryLanguageName: 'دال',
      collectionId: 1,
      categoryId: 4,
      cost: 0.7,
      price: 0.7,
    },
    {
      name: 'Sabji',
      secondaryLanguageName: 'سابجي',
      collectionId: 1,
      categoryId: 4,
      cost: 0.7,
      price: 0.7,
    },
    {
      name: 'Tuna',
      secondaryLanguageName: 'تونة',
      collectionId: 1,
      categoryId: 4,
      cost: 1.2,
      price: 1.2,
    },
    {
      name: 'Phool',
      secondaryLanguageName: 'فول',
      collectionId: 1,
      categoryId: 4,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Pazoli',
      secondaryLanguageName: 'بازولي',
      collectionId: 1,
      categoryId: 4,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Egg Masala',
      secondaryLanguageName: 'البيض ماسالا',
      collectionId: 1,
      categoryId: 4,
      cost: 0.7,
      price: 0.7,
    },
    {
      name: 'Porotta',
      secondaryLanguageName: 'بوروتا',
      collectionId: 1,
      categoryId: 5,
      cost: 0.075,
      price: 0.075,
    },
    {
      name: 'Atta Porotta',
      secondaryLanguageName: 'عطا بوروتا',
      collectionId: 1,
      categoryId: 5,
      cost: 0.075,
      price: 0.075,
    },
    {
      name: 'Chapathy',
      secondaryLanguageName: 'Chapathy',
      collectionId: 1,
      categoryId: 5,
      cost: 0.075,
      price: 0.075,
    },
    {
      name: 'Idiyappam',
      secondaryLanguageName: 'IdiyAppam',
      collectionId: 1,
      categoryId: 5,
      cost: 0.1,
      price: 0.1,
    },
    {
      name: 'Puttu',
      secondaryLanguageName: 'بوتو',
      collectionId: 1,
      categoryId: 5,
      cost: 0.3,
      price: 0.3,
    },
    {
      name: 'Kappa',
      secondaryLanguageName: 'كابا',
      collectionId: 1,
      categoryId: 5,
      cost: 0.4,
      price: 0.4,
    },
    {
      name: 'Seafood Soup',
      secondaryLanguageName: 'شوربة ماكولات بحرية',
      collectionId: 1,
      categoryId: 6,
      cost: 1.3,
      price: 1.3,
    },
    {
      name: 'Sweet Corn Chicken Soup',
      secondaryLanguageName: 'حساء دجاج الذرة الحلو',
      collectionId: 1,
      categoryId: 6,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Sweet Corn Veg Soup',
      secondaryLanguageName: 'حساء الخضار الحلوة',
      collectionId: 1,
      categoryId: 6,
      cost: 0.6,
      price: 0.6,
    },
    {
      name: 'Manchow Soup',
      secondaryLanguageName: 'حساء المانشو',
      collectionId: 1,
      categoryId: 6,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Hto and Sour Soup',
      secondaryLanguageName: 'حساء الحامض والحامض',
      collectionId: 1,
      categoryId: 6,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Fathoush',
      secondaryLanguageName: 'فاثوش',
      collectionId: 1,
      categoryId: 7,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Arabic Salad',
      secondaryLanguageName: 'السلطة العربية',
      collectionId: 1,
      categoryId: 7,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Fresh Green Salad',
      secondaryLanguageName: 'سلطة خضراء جديدة',
      collectionId: 1,
      categoryId: 7,
      cost: 0.8,
      price: 0.8,
    },
    {
      name: 'Dawar Special Salad',
      secondaryLanguageName: 'سلطة دوار الخاصة',
      collectionId: 1,
      categoryId: 7,
      cost: 1,
      price: 1,
    },
    {
      name: 'Hammous',
      secondaryLanguageName: 'الداموس',
      collectionId: 1,
      categoryId: 7,
      cost: 0.6,
      price: 0.6,
    },
    {
      name: 'Squid Nashif',
      secondaryLanguageName: 'الحبار ناشيف',
      collectionId: 1,
      categoryId: 8,
      cost: 1.5,
      price: 1.5,
    },
    {
      name: 'Buttor Squid',
      secondaryLanguageName: 'الأربع الحبار',
      collectionId: 1,
      categoryId: 8,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Squid Chilly',
      secondaryLanguageName: 'حمر باردة',
      collectionId: 1,
      categoryId: 8,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Squid Masala',
      secondaryLanguageName: 'الحبار ماسالا',
      collectionId: 1,
      categoryId: 8,
      cost: 1.5,
      price: 1.5,
    },
    {
      name: 'Squid Fry',
      secondaryLanguageName: 'فراي الحبار',
      collectionId: 1,
      categoryId: 8,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Squid Roast',
      secondaryLanguageName: 'مشوي الحبار',
      collectionId: 1,
      categoryId: 8,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Squid Manchurian',
      secondaryLanguageName: 'Squid Manchurian',
      collectionId: 1,
      categoryId: 8,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Squid Ginger/Garlic',
      secondaryLanguageName: 'زنجبيل الحبار/الثوم',
      collectionId: 1,
      categoryId: 8,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Squid Pepper',
      secondaryLanguageName: 'فلفل الحبار',
      collectionId: 1,
      categoryId: 8,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Sausage Nashif',
      secondaryLanguageName: 'النقانق ناشيف',
      collectionId: 1,
      categoryId: 9,
      cost: 1.2,
      price: 1.2,
    },
    {
      name: 'Sausage Chilly',
      secondaryLanguageName: 'النقانق الباردة',
      collectionId: 1,
      categoryId: 9,
      cost: 1.3,
      price: 1.3,
    },
    {
      name: 'Sausage Butter',
      secondaryLanguageName: 'زبدة النقانق',
      collectionId: 1,
      categoryId: 9,
      cost: 1.4,
      price: 1.4,
    },
    {
      name: 'Sausage Masala',
      secondaryLanguageName: 'سجق ماسالا',
      collectionId: 1,
      categoryId: 9,
      cost: 1.3,
      price: 1.3,
    },
    {
      name: 'Beef Chilly',
      secondaryLanguageName: 'لحوم البقر باردة',
      collectionId: 1,
      categoryId: 10,
      cost: 1.5,
      price: 1.5,
    },
    {
      name: 'Beef Butter',
      secondaryLanguageName: 'زبدة لحوم البقر',
      collectionId: 1,
      categoryId: 10,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Beef Nashif',
      secondaryLanguageName: 'لحوم البقر ناشيف',
      collectionId: 1,
      categoryId: 10,
      cost: 1.3,
      price: 1.3,
    },
    {
      name: 'Beef Masala',
      secondaryLanguageName: 'لحوم البقر ماسالا',
      collectionId: 1,
      categoryId: 10,
      cost: 1.5,
      price: 1.5,
    },
    {
      name: 'Beef Fry',
      secondaryLanguageName: 'بقرية لحوم البقر',
      collectionId: 1,
      categoryId: 10,
      cost: 1.5,
      price: 1.5,
    },
    {
      name: 'Beef Dry Fry',
      secondaryLanguageName: 'لحم بقري جاف',
      collectionId: 1,
      categoryId: 10,
      cost: 1.5,
      price: 1.5,
    },
    {
      name: 'Beef Manchurian',
      secondaryLanguageName: 'لحوم البقر manchurian',
      collectionId: 1,
      categoryId: 10,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Fresh Beef Roast',
      secondaryLanguageName: 'لحم بقري طازج',
      collectionId: 1,
      categoryId: 10,
      cost: 1.5,
      price: 1.5,
    },
    {
      name: 'Beef Peer',
      secondaryLanguageName: 'نظير لحوم البقر',
      collectionId: 1,
      categoryId: 10,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Ginger Garlic Beef',
      secondaryLanguageName: 'اللحم البقري الثوم الزنجبيل',
      collectionId: 1,
      categoryId: 10,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Liver',
      secondaryLanguageName: 'الكبد',
      collectionId: 1,
      categoryId: 10,
      cost: 1.5,
      price: 1.5,
    },
    {
      name: 'Hammous Shawarma',
      secondaryLanguageName: 'شاورما هاموس',
      collectionId: 1,
      categoryId: 11,
      cost: 1.2,
      price: 1.2,
    },
    {
      name: 'Hammous Chicken',
      secondaryLanguageName: 'الدجاج الصاخب',
      collectionId: 1,
      categoryId: 11,
      cost: 1.4,
      price: 1.4,
    },
    {
      name: 'Hammous Squid',
      secondaryLanguageName: 'الحبار الدامس',
      collectionId: 1,
      categoryId: 11,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Hammous Sausage',
      secondaryLanguageName: 'السجق الداموس',
      collectionId: 1,
      categoryId: 11,
      cost: 1.4,
      price: 1.4,
    },
    {
      name: 'Hammous Prawns',
      secondaryLanguageName: 'القريدس الداموس',
      collectionId: 1,
      categoryId: 11,
      cost: 1.6,
      price: 1.6,
    },
    {
      name: 'Hammous Beef',
      secondaryLanguageName: 'لحوم البقر الصاخبة',
      collectionId: 1,
      categoryId: 11,
      cost: 1.4,
      price: 1.4,
    },
  ],
};
