export const july29DawarData = [
  {
    code: 300,
    name: 'Porotta',
    secondaryLanguageName: 'بوروتا',
    cost: 0.05,
    price: 0.05,
    categoryId: 2,
    collectionId: 1,
    qwickViewOrder: 1,
    color: '#eeeee',
  },
  {
    code: 301,
    name: 'Chapati',
    secondaryLanguageName: 'تشاباتي',
    cost: 0.05,
    price: 0.05,
    categoryId: 2,
    collectionId: 1,
    qwickViewOrder: 2,
    color: '#eeeee',
  },
  {
    code: 1,
    name: 'Sabji',
    secondaryLanguageName: 'سابجي',
    cost: 0.7,
    price: 0.7,
    categoryId: 2,
    collectionId: 1,
    qwickViewOrder: 3,
    color: '#eeeee',
  },
  {
    code: 2,
    name: 'Dal ',
    secondaryLanguageName: 'دال',
    cost: 0.7,
    price: 0.7,
    categoryId: 2,
    collectionId: 1,
    qwickViewOrder: 4,
    color: '#eeeee',
  },
  {
    code: 3,
    name: 'Keema',
    secondaryLanguageName: 'كيما',
    cost: 0.7,
    price: 0.7,
    categoryId: 2,
    collectionId: 1,
    qwickViewOrder: 5,
    color: '#eeeee',
  },
  {
    code: 4,
    name: 'Egg Tomato ',
    secondaryLanguageName: 'طماطم البيض',
    cost: 0.7,
    price: 0.7,
    categoryId: 2,
    collectionId: 1,
    qwickViewOrder: 6,
    color: '#eeeee',
  },
  {
    code: 5,
    name: 'Tuna',
    secondaryLanguageName: 'تونة',
    cost: 1,
    price: 1,
    categoryId: 2,
    collectionId: 1,
    qwickViewOrder: 7,
    color: '#eeeee',
  },
  {
    code: 6,
    name: 'Phoole',
    secondaryLanguageName: 'phoole',
    cost: 0.8,
    price: 0.8,
    categoryId: 2,
    collectionId: 1,
    qwickViewOrder: 8,
    color: '#eeeee',
  },
  {
    code: 7,
    name: 'Pazoli',
    secondaryLanguageName: 'بازولي',
    cost: 0.8,
    price: 0.8,
    categoryId: 2,
    collectionId: 1,
    qwickViewOrder: 9,
    color: '#eeeee',
  },
  {
    code: 8,
    name: 'Chicken Biryani ',
    secondaryLanguageName: 'برياني دجاج',
    cost: 1.2,
    price: 1.2,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 10,
    color: '#eeeee',
  },
  {
    code: 9,
    name: '1/2 Chicken Biriyani',
    secondaryLanguageName: '1/2 دجاج بيرياني',
    cost: 1.7,
    price: 1.7,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 11,
    color: '#eeeee',
  },
  {
    code: 10,
    name: 'CB Hyderabadi',
    secondaryLanguageName: 'CB Hyderabadi',
    cost: 1.2,
    price: 1.2,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 12,
    color: '#eeeee',
  },
  {
    code: 11,
    name: '1/2 CB Hyderabadi',
    secondaryLanguageName: '1/2 CB Hyderabadi',
    cost: 1.7,
    price: 1.7,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 13,
    color: '#eeeee',
  },
  {
    code: 12,
    name: 'Mutton Biriyani',
    secondaryLanguageName: 'لحم الضأن بيرياني',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 14,
    color: '#eeeee',
  },
  {
    code: 13,
    name: 'K Biriyani',
    secondaryLanguageName: 'ك برياني',
    cost: 2,
    price: 2,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 15,
    color: '#eeeee',
  },
  {
    code: 14,
    name: 'Shey Biriyani',
    secondaryLanguageName: 'شيري بيرياني',
    cost: 2,
    price: 2,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 16,
    color: '#eeeee',
  },
  {
    code: 15,
    name: 'Rubiyan Biriyani',
    secondaryLanguageName: 'روبيان بيرياني',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 17,
    color: '#eeeee',
  },
  {
    code: 16,
    name: 'Neher Biriyani',
    secondaryLanguageName: 'نهر بيرياني',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 18,
    color: '#eeeee',
  },
  {
    code: 17,
    name: 'R/N Biriyani',
    secondaryLanguageName: 'r/n biriyani',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 19,
    color: '#eeeee',
  },
  {
    code: 18,
    name: 'Fish Biriyani',
    secondaryLanguageName: 'السمك بيرياني',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 20,
    color: '#eeeee',
  },
  {
    code: 19,
    name: 'C Majboos',
    secondaryLanguageName: 'ج ماجبو',
    cost: 1.2,
    price: 1.2,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 21,
    color: '#eeeee',
  },
  {
    code: 20,
    name: '1/2 C Majboos',
    secondaryLanguageName: '1/2 ج ماجبو',
    cost: 1.7,
    price: 1.7,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 22,
    color: '#eeeee',
  },
  {
    code: 21,
    name: 'Mutton Majboos',
    secondaryLanguageName: 'لحم الضأن ماجبو',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 23,
    color: '#eeeee',
  },
  {
    code: 22,
    name: 'Kenal Majboos',
    secondaryLanguageName: 'كينال ماجبو',
    cost: 2,
    price: 2,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 24,
    color: '#eeeee',
  },
  {
    code: 23,
    name: 'Shery Majboos',
    secondaryLanguageName: 'شيري ماجبو',
    cost: 2,
    price: 2,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 25,
    color: '#eeeee',
  },
  {
    code: 24,
    name: 'Fish Majboos',
    secondaryLanguageName: 'ماجبو السمك',
    cost: 2,
    price: 2,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 26,
    color: '#eeeee',
  },
  {
    code: 25,
    name: 'Rubian Majboos',
    secondaryLanguageName: 'روبيان ماجبو',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 27,
    color: '#eeeee',
  },
  {
    code: 26,
    name: 'Neher Majboos',
    secondaryLanguageName: 'Neher Majboos',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 28,
    color: '#eeeee',
  },
  {
    code: 27,
    name: 'R/N Majboos',
    secondaryLanguageName: 'R/N Majboos',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 29,
    color: '#eeeee',
  },
  {
    code: 28,
    name: 'F Prans Majboos',
    secondaryLanguageName: 'و prans majboos',
    cost: 2.5,
    price: 2.5,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 30,
    color: '#eeeee',
  },
  {
    code: 29,
    name: 'F Prans Biriyani',
    secondaryLanguageName: 'و prans biriyani',
    cost: 2.5,
    price: 2.5,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 31,
    color: '#eeeee',
  },
  {
    code: 30,
    name: 'B Rice',
    secondaryLanguageName: 'الأرز ب',
    cost: 0.7,
    price: 0.7,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 32,
    color: '#eeeee',
  },
  {
    code: 31,
    name: 'M Rice',
    secondaryLanguageName: 'م الأرز',
    cost: 0.7,
    price: 0.7,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 33,
    color: '#eeeee',
  },
  {
    code: 32,
    name: 'W Rice',
    secondaryLanguageName: 'أرز',
    cost: 0.6,
    price: 0.6,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 34,
    color: '#eeeee',
  },
  {
    code: 33,
    name: 'B Rice Small',
    secondaryLanguageName: 'B الأرز صغير',
    cost: 0.3,
    price: 0.3,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 35,
    color: '#eeeee',
  },
  {
    code: 34,
    name: 'CF Rice',
    secondaryLanguageName: 'رايس رايس',
    cost: 1.5,
    price: 1.5,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 36,
    color: '#eeeee',
  },
  {
    code: 35,
    name: 'Mix F Rice',
    secondaryLanguageName: 'خلط F الأرز',
    cost: 1.8,
    price: 1.8,
    categoryId: 3,
    collectionId: 1,
    qwickViewOrder: 37,
    color: '#eeeee',
  },
  {
    code: 36,
    name: 'C Dum',
    secondaryLanguageName: 'ج دوم',
    cost: 1.2,
    price: 1.2,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 38,
    color: '#eeeee',
  },
  {
    code: 37,
    name: 'B Dum',
    secondaryLanguageName: 'ب دوم',
    cost: 1.7,
    price: 1.7,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 39,
    color: '#eeeee',
  },
  {
    code: 38,
    name: 'Mutton Dum',
    secondaryLanguageName: 'لحم الضأن دوم',
    cost: 1.8,
    price: 1.8,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 40,
    color: '#eeeee',
  },
  {
    code: 39,
    name: 'Kenal Dum',
    secondaryLanguageName: 'كينال دوم',
    cost: 2,
    price: 2,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 41,
    color: '#eeeee',
  },
  {
    code: 40,
    name: 'Prans Dum',
    secondaryLanguageName: 'برانس دوم',
    cost: 1.8,
    price: 1.8,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 42,
    color: '#eeeee',
  },
  {
    code: 41,
    name: 'F Prans Dum',
    secondaryLanguageName: 'و prans dum',
    cost: 2.5,
    price: 2.5,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 43,
    color: '#eeeee',
  },
  {
    code: 42,
    name: 'Shery Dum',
    secondaryLanguageName: 'شيري دوم',
    cost: 2.5,
    price: 2.5,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 44,
    color: '#eeeee',
  },
  {
    code: 43,
    name: 'Fish Dum',
    secondaryLanguageName: 'السمك',
    cost: 2.5,
    price: 2.5,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 45,
    color: '#eeeee',
  },
  {
    code: 44,
    name: 'C Biriyani Masala',
    secondaryLanguageName: 'C Biriyani Masala',
    cost: 1.2,
    price: 1.2,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 46,
    color: '#eeeee',
  },
  {
    code: 45,
    name: 'Beef Biriyani Masala',
    secondaryLanguageName: 'لحوم البقر بيرياني ماسالا',
    cost: 1.7,
    price: 1.7,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 47,
    color: '#eeeee',
  },
  {
    code: 46,
    name: 'Mutton Biriyani Masala',
    secondaryLanguageName: 'لحم الضأن برياني ماسالا',
    cost: 1.8,
    price: 1.8,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 48,
    color: '#eeeee',
  },
  {
    code: 47,
    name: 'K Biriyani Masala',
    secondaryLanguageName: 'ك برياني ماسالا',
    cost: 2,
    price: 2,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 49,
    color: '#eeeee',
  },
  {
    code: 48,
    name: 'Veg Biriyani',
    secondaryLanguageName: 'الخضار بيرياني',
    cost: 1.1,
    price: 1.1,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 50,
    color: '#eeeee',
  },
  {
    code: 49,
    name: 'Dum B Rice',
    secondaryLanguageName: 'الأرز بدوم ب',
    cost: 0.7,
    price: 0.7,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 51,
    color: '#eeeee',
  },
  {
    code: 50,
    name: 'Gee Rice',
    secondaryLanguageName: 'أرز جي',
    cost: 0.7,
    price: 0.7,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 52,
    color: '#eeeee',
  },
  {
    code: 51,
    name: 'Dum B rice small',
    secondaryLanguageName: 'أرز دوم ب صغير',
    cost: 0.3,
    price: 0.3,
    categoryId: 4,
    collectionId: 1,
    qwickViewOrder: 53,
    color: '#eeeee',
  },
  {
    code: 52,
    name: 'C Nashif',
    secondaryLanguageName: 'ج ناشيف',
    cost: 1.4,
    price: 1.4,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 54,
    color: '#eeeee',
  },
  {
    code: 53,
    name: 'Butter Chicken',
    secondaryLanguageName: 'الدجاج الزبدة',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 55,
    color: '#eeeee',
  },
  {
    code: 54,
    name: 'C Kusasi',
    secondaryLanguageName: 'C Kusasi',
    cost: 1.3,
    price: 1.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 56,
    color: '#eeeee',
  },
  {
    code: 55,
    name: 'C chilly',
    secondaryLanguageName: 'ج باردة',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 57,
    color: '#eeeee',
  },
  {
    code: 56,
    name: 'C 65',
    secondaryLanguageName: 'ج 65',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 58,
    color: '#eeeee',
  },
  {
    code: 57,
    name: 'C smoked',
    secondaryLanguageName: 'ج مدخن',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 59,
    color: '#eeeee',
  },
  {
    code: 58,
    name: 'C ginger gardlic',
    secondaryLanguageName: 'ج الزنجبيل غارديكليك',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 60,
    color: '#eeeee',
  },
  {
    code: 59,
    name: 'C Manchoorian',
    secondaryLanguageName: 'C Manchoorian',
    cost: 1.6,
    price: 1.6,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 61,
    color: '#eeeee',
  },
  {
    code: 60,
    name: 'C Masala',
    secondaryLanguageName: 'ج ماسالا',
    cost: 1.3,
    price: 1.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 62,
    color: '#eeeee',
  },
  {
    code: 61,
    name: 'C Tava',
    secondaryLanguageName: 'ج تافا',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 63,
    color: '#eeeee',
  },
  {
    code: 62,
    name: 'D Sepili Chicken',
    secondaryLanguageName: 'د الدجاج سيبيلي',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 64,
    color: '#eeeee',
  },
  {
    code: 63,
    name: 'Amoose Shawarma',
    secondaryLanguageName: 'Amoose Shawarma',
    cost: 1,
    price: 1,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 65,
    color: '#eeeee',
  },
  {
    code: 64,
    name: 'R Nashif',
    secondaryLanguageName: 'ص ناشيف',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 66,
    color: '#eeeee',
  },
  {
    code: 65,
    name: 'Rubiyan Butter',
    secondaryLanguageName: 'زبدة روبيان',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 67,
    color: '#eeeee',
  },
  {
    code: 66,
    name: 'Rubian Chilly',
    secondaryLanguageName: 'روبيان بارد',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 68,
    color: '#eeeee',
  },
  {
    code: 67,
    name: 'Rubiyan 65',
    secondaryLanguageName: 'روبيان 65',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 69,
    color: '#eeeee',
  },
  {
    code: 68,
    name: 'Rubian Masala',
    secondaryLanguageName: 'روبيان ماسالا',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 70,
    color: '#eeeee',
  },
  {
    code: 69,
    name: 'Rubian Machooriyan',
    secondaryLanguageName: 'روبيان ماتشوريان',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 71,
    color: '#eeeee',
  },
  {
    code: 70,
    name: 'R Smocked',
    secondaryLanguageName: 'ص مدخن',
    cost: 1.8,
    price: 1.8,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 72,
    color: '#eeeee',
  },
  {
    code: 71,
    name: 'R Magil amoose',
    secondaryLanguageName: 'ص ماجيل أموز',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 73,
    color: '#eeeee',
  },
  {
    code: 72,
    name: 'Nehar Nashif',
    secondaryLanguageName: 'نهر ناشيف',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 74,
    color: '#eeeee',
  },
  {
    code: 73,
    name: 'Nehar Butter',
    secondaryLanguageName: 'زبدة نهر',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 75,
    color: '#eeeee',
  },
  {
    code: 74,
    name: 'Nehar Chilly',
    secondaryLanguageName: 'نهر بارد',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 76,
    color: '#eeeee',
  },
  {
    code: 75,
    name: 'Nehar 65',
    secondaryLanguageName: 'نهر 65',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 77,
    color: '#eeeee',
  },
  {
    code: 76,
    name: 'Nehar Smoked',
    secondaryLanguageName: 'نهر يدخن',
    cost: 1.8,
    price: 1.8,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 78,
    color: '#eeeee',
  },
  {
    code: 77,
    name: 'Nehar Manjoorian',
    secondaryLanguageName: 'نهر مانجوريان',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 79,
    color: '#eeeee',
  },
  {
    code: 78,
    name: 'Nehar Masala',
    secondaryLanguageName: 'نهر ماسالا',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 80,
    color: '#eeeee',
  },
  {
    code: 79,
    name: 'Nehar Ginger Garlic',
    secondaryLanguageName: 'ثوم جينجر نهر',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 81,
    color: '#eeeee',
  },
  {
    code: 80,
    name: 'Nehar Magli Amoose',
    secondaryLanguageName: 'نهر ماجلي أموز',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 82,
    color: '#eeeee',
  },
  {
    code: 81,
    name: 'R/Nehar Nashif',
    secondaryLanguageName: 'ص/نهر ناشيف',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 83,
    color: '#eeeee',
  },
  {
    code: 82,
    name: 'R/N Butter',
    secondaryLanguageName: 'ص/زبدة',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 84,
    color: '#eeeee',
  },
  {
    code: 83,
    name: 'R/N chilly',
    secondaryLanguageName: 'ص/ن بارد',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 85,
    color: '#eeeee',
  },
  {
    code: 84,
    name: 'R/N Smoked',
    secondaryLanguageName: 'R/N مدخن',
    cost: 1.8,
    price: 1.8,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 86,
    color: '#eeeee',
  },
  {
    code: 85,
    name: 'R/N Masala',
    secondaryLanguageName: 'R/N Masala',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 87,
    color: '#eeeee',
  },
  {
    code: 86,
    name: 'R/N Magli Hammose',
    secondaryLanguageName: 'R/N Magli Hammose',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 88,
    color: '#eeeee',
  },
  {
    code: 87,
    name: 'R/N Manjoorian',
    secondaryLanguageName: 'ص/ن مانجوريان',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 89,
    color: '#eeeee',
  },
  {
    code: 88,
    name: 'R/N 65',
    secondaryLanguageName: 'ص/ن 65',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 90,
    color: '#eeeee',
  },
  {
    code: 89,
    name: 'R/N Ginger Garlic',
    secondaryLanguageName: 'ص/نجر الثوم',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 91,
    color: '#eeeee',
  },
  {
    code: 90,
    name: 'F Rubiyan Nashif',
    secondaryLanguageName: 'و روبيان ناشيف',
    cost: 2.3,
    price: 2.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 92,
    color: '#eeeee',
  },
  {
    code: 91,
    name: 'F Rubian Butter',
    secondaryLanguageName: 'زبدة روبيان',
    cost: 2.3,
    price: 2.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 93,
    color: '#eeeee',
  },
  {
    code: 92,
    name: 'F Rubian Masala',
    secondaryLanguageName: 'و روبيان ماسالا',
    cost: 2.3,
    price: 2.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 94,
    color: '#eeeee',
  },
  {
    code: 93,
    name: 'F Rubian Chilly',
    secondaryLanguageName: 'و روبيان بارد',
    cost: 2.3,
    price: 2.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 95,
    color: '#eeeee',
  },
  {
    code: 94,
    name: 'F Rubina 65',
    secondaryLanguageName: 'F Rubina 65',
    cost: 2.3,
    price: 2.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 96,
    color: '#eeeee',
  },
  {
    code: 95,
    name: 'F Rubian Smoked',
    secondaryLanguageName: 'و روبيان يدخن',
    cost: 2.3,
    price: 2.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 97,
    color: '#eeeee',
  },
  {
    code: 96,
    name: 'F Rubian Manjoorian',
    secondaryLanguageName: 'و روبيان مانجوريان',
    cost: 2.3,
    price: 2.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 98,
    color: '#eeeee',
  },
  {
    code: 97,
    name: 'F Rubian Magli Ammose',
    secondaryLanguageName: 'و روبيان ماجلي',
    cost: 2.3,
    price: 2.3,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 99,
    color: '#eeeee',
  },
  {
    code: 98,
    name: 'Nakenak Nashif',
    secondaryLanguageName: 'ناكيناك ناشيف',
    cost: 1,
    price: 1,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 100,
    color: '#eeeee',
  },
  {
    code: 99,
    name: 'Nakenak Masala',
    secondaryLanguageName: 'ناكيناك ماسالا',
    cost: 1.2,
    price: 1.2,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 101,
    color: '#eeeee',
  },
  {
    code: 100,
    name: 'Nakenak Butter',
    secondaryLanguageName: 'زبدة ناكيناك',
    cost: 1.2,
    price: 1.2,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 102,
    color: '#eeeee',
  },
  {
    code: 101,
    name: 'Nakenak Magli Ammose',
    secondaryLanguageName: 'Nakenak Magli Ammose',
    cost: 1.2,
    price: 1.2,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 103,
    color: '#eeeee',
  },
  {
    code: 102,
    name: 'Nakenak Chilly',
    secondaryLanguageName: 'نياك بارد',
    cost: 1.2,
    price: 1.2,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 104,
    color: '#eeeee',
  },
  {
    code: 103,
    name: 'Lahem Nashif',
    secondaryLanguageName: 'لاهيم ناشيف',
    cost: 1.4,
    price: 1.4,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 105,
    color: '#eeeee',
  },
  {
    code: 104,
    name: 'Hammose Leham',
    secondaryLanguageName: 'هامس ليهام',
    cost: 1.4,
    price: 1.4,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 106,
    color: '#eeeee',
  },
  {
    code: 105,
    name: 'Beef Butter',
    secondaryLanguageName: 'زبدة لحوم البقر',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 107,
    color: '#eeeee',
  },
  {
    code: 106,
    name: 'Egg Tomato',
    secondaryLanguageName: 'طماطم البيض',
    cost: 0.7,
    price: 0.7,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 108,
    color: '#eeeee',
  },
  {
    code: 107,
    name: 'Mutton Masala',
    secondaryLanguageName: 'لحم الضأن ماسالا',
    cost: 1.5,
    price: 1.5,
    categoryId: 5,
    collectionId: 1,
    qwickViewOrder: 109,
    color: '#eeeee',
  },
  {
    code: 108,
    name: 'Beef Rost',
    secondaryLanguageName: 'لحم البقر',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 110,
    color: '#eeeee',
  },
  {
    code: 109,
    name: 'Beef Fry',
    secondaryLanguageName: 'بقرية لحوم البقر',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 111,
    color: '#eeeee',
  },
  {
    code: 110,
    name: 'Beef Curry',
    secondaryLanguageName: 'لحم البقر بالكاري',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 112,
    color: '#eeeee',
  },
  {
    code: 111,
    name: 'Liver',
    secondaryLanguageName: 'الكبد',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 113,
    color: '#eeeee',
  },
  {
    code: 112,
    name: 'Botti',
    secondaryLanguageName: 'بوتي',
    cost: 1.3,
    price: 1.3,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 114,
    color: '#eeeee',
  },
  {
    code: 113,
    name: 'Duck',
    secondaryLanguageName: 'بطة',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 115,
    color: '#eeeee',
  },
  {
    code: 114,
    name: 'Ayla Curry',
    secondaryLanguageName: 'Ayla كاري',
    cost: 1.2,
    price: 1.2,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 116,
    color: '#eeeee',
  },
  {
    code: 115,
    name: 'Avoli Curry',
    secondaryLanguageName: 'أفولي كاري',
    cost: 1.4,
    price: 1.4,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 117,
    color: '#eeeee',
  },
  {
    code: 116,
    name: 'Mutton Pepper',
    secondaryLanguageName: 'فلفل لحم الضأن',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 118,
    color: '#eeeee',
  },
  {
    code: 117,
    name: 'Crab',
    secondaryLanguageName: 'سلطعون',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 119,
    color: '#eeeee',
  },
  {
    code: 118,
    name: 'Koonthel Rost',
    secondaryLanguageName: 'Koonthel Rost',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 120,
    color: '#eeeee',
  },
  {
    code: 119,
    name: 'C Pepper Masala',
    secondaryLanguageName: 'ج الفلفل ماسالا',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 121,
    color: '#eeeee',
  },
  {
    code: 120,
    name: 'C Kadai',
    secondaryLanguageName: 'ج كاداي',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 122,
    color: '#eeeee',
  },
  {
    code: 121,
    name: 'C Chilly',
    secondaryLanguageName: 'ج باردة',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 123,
    color: '#eeeee',
  },
  {
    code: 122,
    name: 'C 65',
    secondaryLanguageName: 'ج 65',
    cost: 1.4,
    price: 1.4,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 124,
    color: '#eeeee',
  },
  {
    code: 123,
    name: 'C Kerala',
    secondaryLanguageName: 'ج كيرالا',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 125,
    color: '#eeeee',
  },
  {
    code: 124,
    name: 'C Asiyana',
    secondaryLanguageName: 'C Asiyana',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 126,
    color: '#eeeee',
  },
  {
    code: 125,
    name: 'C Kuruma',
    secondaryLanguageName: 'ج كوروما',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 127,
    color: '#eeeee',
  },
  {
    code: 126,
    name: 'C Chettinadu',
    secondaryLanguageName: 'C Chettinadu',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 128,
    color: '#eeeee',
  },
  {
    code: 127,
    name: 'Chicken Stew',
    secondaryLanguageName: 'حساء الدجاج',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 129,
    color: '#eeeee',
  },
  {
    code: 128,
    name: 'Chicken Rost',
    secondaryLanguageName: 'دجاج روست',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 130,
    color: '#eeeee',
  },
  {
    code: 129,
    name: 'Pepper Chilly',
    secondaryLanguageName: 'الفلفل بارد',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 131,
    color: '#eeeee',
  },
  {
    code: 130,
    name: 'C Smoked',
    secondaryLanguageName: 'ج مدخن',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 132,
    color: '#eeeee',
  },
  {
    code: 131,
    name: 'Fish Rost',
    secondaryLanguageName: 'صخور الأسماك',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 133,
    color: '#eeeee',
  },
  {
    code: 132,
    name: 'Prans Rost',
    secondaryLanguageName: 'برانس روست',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 134,
    color: '#eeeee',
  },
  {
    code: 133,
    name: 'F Prans Rost',
    secondaryLanguageName: 'و prans rost',
    cost: 2.3,
    price: 2.3,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 135,
    color: '#eeeee',
  },
  {
    code: 134,
    name: 'Chicken Sachwan',
    secondaryLanguageName: 'دجاج ساشوان',
    cost: 1.5,
    price: 1.5,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 136,
    color: '#eeeee',
  },
  {
    code: 135,
    name: 'Chicken Masala',
    secondaryLanguageName: 'دجاج ماسالا',
    cost: 1.3,
    price: 1.3,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 137,
    color: '#eeeee',
  },
  {
    code: 136,
    name: 'Vej Kuruma',
    secondaryLanguageName: 'فيج كوروما',
    cost: 0.8,
    price: 0.8,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 138,
    color: '#eeeee',
  },
  {
    code: 137,
    name: 'Paneer Masala',
    secondaryLanguageName: 'بانير ماسالا',
    cost: 1.2,
    price: 1.2,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 139,
    color: '#eeeee',
  },
  {
    code: 138,
    name: 'Paneel Butter',
    secondaryLanguageName: 'زبدة paneel',
    cost: 1.2,
    price: 1.2,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 140,
    color: '#eeeee',
  },
  {
    code: 139,
    name: 'Paneer Kadai',
    secondaryLanguageName: 'بانير كاداي',
    cost: 1.2,
    price: 1.2,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 141,
    color: '#eeeee',
  },
  {
    code: 140,
    name: 'Paneer Buruji',
    secondaryLanguageName: 'بانير بوروجي',
    cost: 1.2,
    price: 1.2,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 142,
    color: '#eeeee',
  },
  {
    code: 141,
    name: 'Mashroom Masala',
    secondaryLanguageName: 'مهجور ماسالا',
    cost: 1.2,
    price: 1.2,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 143,
    color: '#eeeee',
  },
  {
    code: 142,
    name: 'Mashroom Kadai',
    secondaryLanguageName: 'المهجور كاداي',
    cost: 1.2,
    price: 1.2,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 144,
    color: '#eeeee',
  },
  {
    code: 143,
    name: 'Gobi Manjoorian',
    secondaryLanguageName: 'جوبي مانجوريان',
    cost: 1.2,
    price: 1.2,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 145,
    color: '#eeeee',
  },
  {
    code: 144,
    name: 'Chilly Gobi',
    secondaryLanguageName: 'جوبي البارد',
    cost: 1.2,
    price: 1.2,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 146,
    color: '#eeeee',
  },
  {
    code: 145,
    name: 'Egg Burji',
    secondaryLanguageName: 'بيضة بورجي',
    cost: 0.8,
    price: 0.8,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 147,
    color: '#eeeee',
  },
  {
    code: 146,
    name: 'Porotta',
    secondaryLanguageName: 'بوروتا',
    cost: 0.05,
    price: 0.05,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 148,
    color: '#eeeee',
  },
  {
    code: 147,
    name: 'Atta Porotta',
    secondaryLanguageName: 'عطا بوروتا',
    cost: 0.05,
    price: 0.05,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 149,
    color: '#eeeee',
  },
  {
    code: 148,
    name: 'Chapati',
    secondaryLanguageName: 'تشاباتي',
    cost: 0.05,
    price: 0.05,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 150,
    color: '#eeeee',
  },
  {
    code: 149,
    name: 'Idiyappam',
    secondaryLanguageName: 'IdiyAppam',
    cost: 0.1,
    price: 0.1,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 151,
    color: '#eeeee',
  },
  {
    code: 150,
    name: 'Kappa',
    secondaryLanguageName: 'كابا',
    cost: 0.4,
    price: 0.4,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 152,
    color: '#eeeee',
  },
  {
    code: 151,
    name: 'Gee Rice',
    secondaryLanguageName: 'أرز جي',
    cost: 0.7,
    price: 0.7,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 153,
    color: '#eeeee',
  },
  {
    code: 152,
    name: 'W Rice',
    secondaryLanguageName: 'أرز',
    cost: 0.7,
    price: 0.7,
    categoryId: 6,
    collectionId: 1,
    qwickViewOrder: 154,
    color: '#eeeee',
  },
  {
    code: 153,
    name: 'Butter C Rice',
    secondaryLanguageName: 'زبدة الأرز',
    cost: 1.8,
    price: 1.8,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 155,
    color: '#eeeee',
  },
  {
    code: 154,
    name: 'Mutton Masala Rice',
    secondaryLanguageName: 'لحم الضأن ماسالا',
    cost: 1.8,
    price: 1.8,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 156,
    color: '#eeeee',
  },
  {
    code: 155,
    name: 'Rubian Masala Rice',
    secondaryLanguageName: 'روبيان ماسالا الأرز',
    cost: 1.8,
    price: 1.8,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 157,
    color: '#eeeee',
  },
  {
    code: 156,
    name: 'Fish Masala Rice',
    secondaryLanguageName: 'الأرز ماسالا السمك',
    cost: 1.8,
    price: 1.8,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 158,
    color: '#eeeee',
  },
  {
    code: 157,
    name: 'R Butter Rice',
    secondaryLanguageName: 'ص الأرز الزبدة',
    cost: 1.8,
    price: 1.8,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 159,
    color: '#eeeee',
  },
  {
    code: 158,
    name: 'C Masala Rice',
    secondaryLanguageName: 'ج ماسالا الأرز',
    cost: 1.5,
    price: 1.5,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 160,
    color: '#eeeee',
  },
  {
    code: 159,
    name: 'Nehar Masala Rice',
    secondaryLanguageName: 'رايس نهر ماسالا',
    cost: 1.8,
    price: 1.8,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 161,
    color: '#eeeee',
  },
  {
    code: 160,
    name: 'Ghee Rice Beef rost',
    secondaryLanguageName: 'السمن رايس لحم البقر',
    cost: 1.8,
    price: 1.8,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 162,
    color: '#eeeee',
  },
  {
    code: 161,
    name: 'G Rice C Curry',
    secondaryLanguageName: 'G الأرز C Curry',
    cost: 1.8,
    price: 1.8,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 163,
    color: '#eeeee',
  },
  {
    code: 162,
    name: 'B Rice',
    secondaryLanguageName: 'الأرز ب',
    cost: 0.7,
    price: 0.7,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 164,
    color: '#eeeee',
  },
  {
    code: 163,
    name: 'W Rice',
    secondaryLanguageName: 'أرز',
    cost: 0.7,
    price: 0.7,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 165,
    color: '#eeeee',
  },
  {
    code: 164,
    name: 'G Rice',
    secondaryLanguageName: 'رايس',
    cost: 0.7,
    price: 0.7,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 166,
    color: '#eeeee',
  },
  {
    code: 165,
    name: 'Rice Small',
    secondaryLanguageName: 'الأرز صغير',
    cost: 0.3,
    price: 0.3,
    categoryId: 7,
    collectionId: 1,
    qwickViewOrder: 167,
    color: '#eeeee',
  },
  {
    code: 166,
    name: 'C Fried Rice',
    secondaryLanguageName: 'ج الأرز المقلي',
    cost: 1.5,
    price: 1.5,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 168,
    color: '#eeeee',
  },
  {
    code: 167,
    name: 'Veg Fried Rice',
    secondaryLanguageName: 'الأرز الخضار المقلي',
    cost: 1.2,
    price: 1.2,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 169,
    color: '#eeeee',
  },
  {
    code: 168,
    name: 'Egg Fried Rice',
    secondaryLanguageName: 'الأرز المقلي البيض',
    cost: 1.3,
    price: 1.3,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 170,
    color: '#eeeee',
  },
  {
    code: 169,
    name: 'Mix Fried Rice',
    secondaryLanguageName: 'خلط الأرز المقلي',
    cost: 1.8,
    price: 1.8,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 171,
    color: '#eeeee',
  },
  {
    code: 170,
    name: 'Seshwan Fried Rice',
    secondaryLanguageName: 'سيشوان الأرز المقلي',
    cost: 1.8,
    price: 1.8,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 172,
    color: '#eeeee',
  },
  {
    code: 171,
    name: 'C Chilly',
    secondaryLanguageName: 'ج باردة',
    cost: 1.5,
    price: 1.5,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 173,
    color: '#eeeee',
  },
  {
    code: 172,
    name: 'C Manjoorian',
    secondaryLanguageName: 'ج مانجوريان',
    cost: 1.5,
    price: 1.5,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 174,
    color: '#eeeee',
  },
  {
    code: 173,
    name: 'C Smoked',
    secondaryLanguageName: 'ج مدخن',
    cost: 1.5,
    price: 1.5,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 175,
    color: '#eeeee',
  },
  {
    code: 174,
    name: 'C 65',
    secondaryLanguageName: 'ج 65',
    cost: 1.4,
    price: 1.4,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 176,
    color: '#eeeee',
  },
  {
    code: 175,
    name: 'W Rice',
    secondaryLanguageName: 'أرز',
    cost: 0.7,
    price: 0.7,
    categoryId: 8,
    collectionId: 1,
    qwickViewOrder: 177,
    color: '#eeeee',
  },
  {
    code: 176,
    name: 'See Food Soup',
    secondaryLanguageName: 'انظر حساء الطعام',
    cost: 1.2,
    price: 1.2,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 178,
    color: '#eeeee',
  },
  {
    code: 177,
    name: 'Sweet Corn Soup',
    secondaryLanguageName: 'حساء الذرة الحلو',
    cost: 0.8,
    price: 0.8,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 179,
    color: '#eeeee',
  },
  {
    code: 178,
    name: 'Sweet Corn Veg Soup',
    secondaryLanguageName: 'حساء الخضار الحلوة',
    cost: 0.6,
    price: 0.6,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 180,
    color: '#eeeee',
  },
  {
    code: 179,
    name: 'Hot & Sour Soup',
    secondaryLanguageName: 'الحساء الساخن والحامض',
    cost: 0.8,
    price: 0.8,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 181,
    color: '#eeeee',
  },
  {
    code: 180,
    name: 'Hot & Sour Veg Soup',
    secondaryLanguageName: 'حساء الخضار الساخن والحامض',
    cost: 0.6,
    price: 0.6,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 182,
    color: '#eeeee',
  },
  {
    code: 181,
    name: 'Chicken Manchow Soup',
    secondaryLanguageName: 'شوربة مانشو الدجاج',
    cost: 0.8,
    price: 0.8,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 183,
    color: '#eeeee',
  },
  {
    code: 182,
    name: 'Veg Manchaw Soup',
    secondaryLanguageName: 'حساء الخضار مانشو',
    cost: 0.6,
    price: 0.6,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 184,
    color: '#eeeee',
  },
  {
    code: 183,
    name: 'Fathoosh',
    secondaryLanguageName: 'Fathoosh',
    cost: 0.8,
    price: 0.8,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 185,
    color: '#eeeee',
  },
  {
    code: 184,
    name: 'Arabic Salad',
    secondaryLanguageName: 'السلطة العربية',
    cost: 0.8,
    price: 0.8,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 186,
    color: '#eeeee',
  },
  {
    code: 185,
    name: 'Fresh Green Salad',
    secondaryLanguageName: 'سلطة خضراء جديدة',
    cost: 0.8,
    price: 0.8,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 187,
    color: '#eeeee',
  },
  {
    code: 186,
    name: 'Dawar Special Salad',
    secondaryLanguageName: 'سلطة دوار الخاصة',
    cost: 0.8,
    price: 0.8,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 188,
    color: '#eeeee',
  },
  {
    code: 187,
    name: 'Favaka',
    secondaryLanguageName: 'فافاكا',
    cost: 1,
    price: 1,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 189,
    color: '#eeeee',
  },
  {
    code: 188,
    name: 'Hamoos Small',
    secondaryLanguageName: 'Hamoos صغيرة',
    cost: 0.3,
    price: 0.3,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 190,
    color: '#eeeee',
  },
  {
    code: 189,
    name: 'Hamose Big',
    secondaryLanguageName: 'هاموز كبير',
    cost: 0.6,
    price: 0.6,
    categoryId: 9,
    collectionId: 1,
    qwickViewOrder: 191,
    color: '#eeeee',
  },
  {
    code: 190,
    name: 'Shavarma',
    secondaryLanguageName: 'شافارما',
    cost: 0.3,
    price: 0.3,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 192,
    color: '#eeeee',
  },
  {
    code: 191,
    name: 'Shavarma Sarook',
    secondaryLanguageName: 'Shavarma Sarook',
    cost: 0.7,
    price: 0.7,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 193,
    color: '#eeeee',
  },
  {
    code: 192,
    name: 'Beef Sandwich',
    secondaryLanguageName: 'شطيرة لحوم البقر',
    cost: 0.3,
    price: 0.3,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 194,
    color: '#eeeee',
  },
  {
    code: 193,
    name: 'Rubiyan Sandwich',
    secondaryLanguageName: 'شطيرة روبيان',
    cost: 0.4,
    price: 0.4,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 195,
    color: '#eeeee',
  },
  {
    code: 194,
    name: 'Nehar Sandwich',
    secondaryLanguageName: 'ساندويتش نهر',
    cost: 0.4,
    price: 0.4,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 196,
    color: '#eeeee',
  },
  {
    code: 195,
    name: 'R/N Sandwich',
    secondaryLanguageName: 'R/N Sandwich',
    cost: 0.4,
    price: 0.4,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 197,
    color: '#eeeee',
  },
  {
    code: 196,
    name: 'Egg Jiben Porotta',
    secondaryLanguageName: 'البيض جيبن بوروتا',
    cost: 0.2,
    price: 0.2,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 198,
    color: '#eeeee',
  },
  {
    code: 197,
    name: 'Jiben Porotta',
    secondaryLanguageName: 'جيبن بوروتا',
    cost: 0.1,
    price: 0.1,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 199,
    color: '#eeeee',
  },
  {
    code: 198,
    name: 'Nakanek Sandwich',
    secondaryLanguageName: 'ساندويتش ناكانيك',
    cost: 0.2,
    price: 0.2,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 200,
    color: '#eeeee',
  },
  {
    code: 199,
    name: 'Filafil',
    secondaryLanguageName: 'filafil',
    cost: 0.25,
    price: 0.25,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 201,
    color: '#eeeee',
  },
  {
    code: 200,
    name: 'Tika Sarook',
    secondaryLanguageName: 'تيكا ساروك',
    cost: 0.7,
    price: 0.7,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 202,
    color: '#eeeee',
  },
  {
    code: 201,
    name: 'Kabab Sarook',
    secondaryLanguageName: 'كاباب ساروك',
    cost: 0.7,
    price: 0.7,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 203,
    color: '#eeeee',
  },
  {
    code: 202,
    name: 'Beef Sarook',
    secondaryLanguageName: 'لحوم البقر ساروك',
    cost: 0.7,
    price: 0.7,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 204,
    color: '#eeeee',
  },
  {
    code: 203,
    name: 'Chips Small',
    secondaryLanguageName: 'رقائق صغيرة',
    cost: 0.3,
    price: 0.3,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 205,
    color: '#eeeee',
  },
  {
    code: 204,
    name: 'Chips Big',
    secondaryLanguageName: 'رقائق كبيرة',
    cost: 0.5,
    price: 0.5,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 206,
    color: '#eeeee',
  },
  {
    code: 205,
    name: 'Wedjes',
    secondaryLanguageName: 'Wedjes',
    cost: 0.8,
    price: 0.8,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 207,
    color: '#eeeee',
  },
  {
    code: 206,
    name: 'Wedjes Big',
    secondaryLanguageName: 'Wedjes كبير',
    cost: 1,
    price: 1,
    categoryId: 10,
    collectionId: 1,
    qwickViewOrder: 208,
    color: '#eeeee',
  },
  {
    code: 207,
    name: 'Mango',
    secondaryLanguageName: 'مانجو',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 209,
    color: '#eeeee',
  },
  {
    code: 208,
    name: 'Avocado',
    secondaryLanguageName: 'أفوكادو',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 210,
    color: '#eeeee',
  },
  {
    code: 209,
    name: 'Banana',
    secondaryLanguageName: 'موز',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 211,
    color: '#eeeee',
  },
  {
    code: 210,
    name: 'Pinapple',
    secondaryLanguageName: 'Pinapple',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 212,
    color: '#eeeee',
  },
  {
    code: 211,
    name: 'Lemonade',
    secondaryLanguageName: 'عصير الليمون',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 213,
    color: '#eeeee',
  },
  {
    code: 212,
    name: 'Water Melone',
    secondaryLanguageName: 'ماء ميلوني',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 214,
    color: '#eeeee',
  },
  {
    code: 213,
    name: 'Orange',
    secondaryLanguageName: 'البرتقالي',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 215,
    color: '#eeeee',
  },
  {
    code: 214,
    name: 'Falooda',
    secondaryLanguageName: 'فالودا',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 216,
    color: '#eeeee',
  },
  {
    code: 215,
    name: 'Abood',
    secondaryLanguageName: 'معتدل',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 217,
    color: '#eeeee',
  },
  {
    code: 216,
    name: 'Anar',
    secondaryLanguageName: 'أنار',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 218,
    color: '#eeeee',
  },
  {
    code: 217,
    name: 'Cocktail',
    secondaryLanguageName: 'كوكتيل',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 219,
    color: '#eeeee',
  },
  {
    code: 218,
    name: '50x50',
    secondaryLanguageName: '50x50',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 220,
    color: '#eeeee',
  },
  {
    code: 219,
    name: 'Tavakath',
    secondaryLanguageName: 'تافاكاث',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 221,
    color: '#eeeee',
  },
  {
    code: 220,
    name: 'Taitanic',
    secondaryLanguageName: 'taitanic',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 222,
    color: '#eeeee',
  },
  {
    code: 221,
    name: 'Burj Al Arab',
    secondaryLanguageName: 'برج العرب',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 223,
    color: '#eeeee',
  },
  {
    code: 222,
    name: 'Cocktail Omani',
    secondaryLanguageName: 'كوكتيل عماني',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 224,
    color: '#eeeee',
  },
  {
    code: 223,
    name: 'Cocktail Kuwaiti',
    secondaryLanguageName: 'كوكتيل الكويتي',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 225,
    color: '#eeeee',
  },
  {
    code: 224,
    name: 'Glory',
    secondaryLanguageName: 'مجد',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 226,
    color: '#eeeee',
  },
  {
    code: 225,
    name: 'Al Dawar Special',
    secondaryLanguageName: 'داور خاص',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 227,
    color: '#eeeee',
  },
  {
    code: 226,
    name: 'Welcome 2022',
    secondaryLanguageName: 'مرحبا بكم 2022',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 228,
    color: '#eeeee',
  },
  {
    code: 227,
    name: 'Fresh Lime Soda',
    secondaryLanguageName: 'الصودا الجير الطازجة',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 229,
    color: '#eeeee',
  },
  {
    code: 228,
    name: 'Water',
    secondaryLanguageName: 'ماء',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 230,
    color: '#eeeee',
  },
  {
    code: 229,
    name: 'Drinks',
    secondaryLanguageName: 'مشروبات',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 231,
    color: '#eeeee',
  },
  {
    code: 230,
    name: 'Chips',
    secondaryLanguageName: 'رقائق',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 232,
    color: '#eeeee',
  },
  {
    code: 231,
    name: 'Wedjes',
    secondaryLanguageName: 'Wedjes',
    cost: 0.3,
    price: 0.3,
    categoryId: 11,
    collectionId: 1,
    qwickViewOrder: 233,
    color: '#eeeee',
  },
  {
    code: 232,
    name: 'C Burger',
    secondaryLanguageName: 'ج برغر',
    cost: 0.5,
    price: 0.5,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 234,
    color: '#eeeee',
  },
  {
    code: 233,
    name: 'Beef Burger',
    secondaryLanguageName: 'برغر لحوم البقر',
    cost: 0.5,
    price: 0.5,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 235,
    color: '#eeeee',
  },
  {
    code: 234,
    name: 'Veg Burger',
    secondaryLanguageName: 'برجر الخضار',
    cost: 0.6,
    price: 0.6,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 236,
    color: '#eeeee',
  },
  {
    code: 235,
    name: 'Double Berger',
    secondaryLanguageName: 'بيرغر مزدوج',
    cost: 1,
    price: 1,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 237,
    color: '#eeeee',
  },
  {
    code: 236,
    name: 'Mega Zinger Berger',
    secondaryLanguageName: 'ميجا Zinger Berger',
    cost: 1.2,
    price: 1.2,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 238,
    color: '#eeeee',
  },
  {
    code: 237,
    name: 'Zinger Burger',
    secondaryLanguageName: 'Zinger Burger',
    cost: 0.6,
    price: 0.6,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 239,
    color: '#eeeee',
  },
  {
    code: 238,
    name: 'Kentucky Burger',
    secondaryLanguageName: 'كنتاكي برجر',
    cost: 0.8,
    price: 0.8,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 240,
    color: '#eeeee',
  },
  {
    code: 239,
    name: 'Sheesh Tavook Burger',
    secondaryLanguageName: 'شيش تافوك برجر',
    cost: 0.7,
    price: 0.7,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 241,
    color: '#eeeee',
  },
  {
    code: 240,
    name: 'C Burger Special',
    secondaryLanguageName: 'C Burger Special',
    cost: 0.6,
    price: 0.6,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 242,
    color: '#eeeee',
  },
  {
    code: 241,
    name: 'Hot Dog Burger',
    secondaryLanguageName: 'برجر هوت دوج',
    cost: 0.6,
    price: 0.6,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 243,
    color: '#eeeee',
  },
  {
    code: 242,
    name: 'C Tandoori Burger',
    secondaryLanguageName: 'C Tandoori Burger',
    cost: 0.5,
    price: 0.5,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 244,
    color: '#eeeee',
  },
  {
    code: 243,
    name: 'Jumbo Prans Burger',
    secondaryLanguageName: 'Jumbo Prans Burger',
    cost: 0.6,
    price: 0.6,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 245,
    color: '#eeeee',
  },
  {
    code: 244,
    name: 'C Lemone Burger',
    secondaryLanguageName: 'C Lemone Burger',
    cost: 0.5,
    price: 0.5,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 246,
    color: '#eeeee',
  },
  {
    code: 245,
    name: 'Cajun Burger ',
    secondaryLanguageName: 'كاجون برجر',
    cost: 0.5,
    price: 0.5,
    categoryId: 12,
    collectionId: 1,
    qwickViewOrder: 247,
    color: '#eeeee',
  },
];
